### ISSUE TITLE
go版本用数据库连接报错

### ISSUE THREAD

**Issue by echoowall** [orvice/shadowsocks-go#27]
ERRO[0000] boot redis fail: dial tcp [::1]:6379: getsockopt: connection refused

**Comment by echoowall** [comment]
刚才是redis的问题，解决了以后出现这个问题
INFO[0000] PONG  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401118]

goroutine 1 [running]:
panic(0x97c400, 0xc82000a0f0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.boot()
    /root/gowork/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x118
main.main()
    /root/gowork/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x28f
