### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by relei1988** [orvice/shadowsocks-go#50]
似乎都设置正确,但是不知道问题出在哪..

```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go/go/gopath"
GORACE=""
GOROOT="/root/go/go"
GOTOOLDIR="/root/go/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

go version go1.6.2 linux/amd64

```
# ./mu -debug
INFO[0000] PONG
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401118]

goroutine 1 [running]:
panic(0x992fc0, 0xc82000a100)
        /root/go/go/src/runtime/panic.go:481 +0x3e6
main.boot()
        /root/go/go/gopath/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x118
main.main()
        /root/go/go/gopath/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x28f
```

求帮忙看下

**Comment by webcjz** [comment]
出现了同样的问题，有解决方案吗

**Comment by webcjz** [comment]
@relei1988 已解决，要正确填写config.conf mysql 项
