### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kyledh** [orvice/shadowsocks-go#6]
执行 ./mu 后，出现以下错误，go 版本为 1.6

```
root@linux:/root/go/src/github.com/orvice/shadowsocks-go/mu# ./mu
INFO[0000] PONG
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401118]

goroutine 1 [running]:
panic(0x98cc40, 0xc82000a0d0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.boot()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x118
main.main()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x28f
```

**Comment by orvice** [comment]
配置文件发下

**Comment by kyledh** [comment]
config.conf

```
## 配置说明  https://github.com/orvice/shadowsocks-gg
o/wiki/Config
[base]
N 1
ip 0.0.0.0
client mysql
checktime  60
synctime   60

[webapi]
url http://sspanel.dev/mu
key key
node_id 1

[mysql]
host  127.0.0.1:3306
user root
pass root
db   db
table sspanel

[redis]
host localhost:6379
# if no passwd set,comment this line
# pass ""
db 1
```

**Comment by orvice** [comment]
checkout到mu分支编译了？

**Comment by kyledh** [comment]
是的，操作有错误？

**Comment by orvice** [comment]
golang 1.5.3编译试试看？
1.6我还没测试

**Comment by kyledh** [comment]
好的，今天太晚了，明天再尝试😅

**Comment by kyledh** [comment]
切换到1.5.3了，出现以下错误

```
root@linux:~/go/src/github.com/orvice/shadowsocks-go/mu# ./mu
INFO[0000] PONG                                         
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401127]

goroutine 1 [running]:
main.boot()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x127
main.main()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x2a3

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8201b68c0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336
```

操作过程：

```
root@linux:~# git clone -b mu https://github.com/orvice/shadowsocks-go.git
root@linux:~# cd ~/shadowsocks-go/mu
root@linux:~/shadowsocks-go/mu# go get
go install: no install location for directory /root/shadowsocks-go/mu outside GOPATH
    For more details see: go help gopath
root@linux:~/shadowsocks-go/mu# cd ~/go/src/github.com/orvice/shadowsocks-go
root@linux:~/go/src/github.com/orvice/shadowsocks-go# git checkout mu
root@linux:~/go/src/github.com/orvice/shadowsocks-go# cd mu/
root@linux:~/go/src/github.com/orvice/shadowsocks-go/mu# go get
root@linux:~/go/src/github.com/orvice/shadowsocks-go/mu# go build
root@linux:~/go/src/github.com/orvice/shadowsocks-go/mu# go ./mu
INFO[0000] PONG                                         
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x401127]

goroutine 1 [running]:
main.boot()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/boot.go:31 +0x127
main.main()
    /root/go/src/github.com/orvice/shadowsocks-go/mu/main.go:31 +0x2a3

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8201b68c0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336
```

go env

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by orvice** [comment]
用web api模式呢？

**Comment by kyledh** [comment]
使用web api模式可以，但是无法翻墙，并且更改密码端口等会出现错误

```
root@linux:~/go/src/github.com/orvice/shadowsocks-go/mu# ./mu
INFO[0000] PONG
INFO[0000] 1
INFO[0000] 1
INFO[0000] 1
INFO[0000] new user to run{1 1025 qQqrdZ rc4-md5 1 5368709120 0 0}
INFO[0000] check finish...
INFO[0000] server listening port 1025 ...

INFO[0000] 1
INFO[0000] sync finish...
INFO[0060] 1
INFO[0060] sync finish...
INFO[0060] 1
INFO[0060] user port [1025] passwd or method change ,restart user...
INFO[0060] check finish...
ERRO[0060] error listening port 1025: listen tcp :1025: bind: address already in use
```

**Comment by orvice** [comment]
标记下，晚上我确认下

**Comment by orvice** [comment]
./mu -debug
这样跑下，在发下log

**Comment by kyledh** [comment]
log

```
DEBU[0000] debug on
INFO[0000] PONG
INFO[0000] 1
INFO[0000] sync finish...
DEBU[0000] [{1 1025 qwe123 rc4-md5 1 5368709120 0 0}]
DEBU[0000] check user for 1025
INFO[0000] new user to run{1 1025 qwe123 rc4-md5 1 5368709120 0 0}
INFO[0000] check finish...
INFO[0000] server listening port 1025 ...

INFO[0060] sync finish...
DEBU[0060] [{1 1025 asd123 rc4-md5 1 5368709120 0 0}]
DEBU[0060] check user for 1025
INFO[0060] user port [1025] passwd or method change ,restart user...
INFO[0060] check finish...
ERRO[0060] error listening port 1025: listen tcp :1025: bind: address already in use
```

**Comment by glzjin** [comment]
表示也出现了一换密码和加密方式就跪的问题，目前用 supervisor 先撑着了。

**Comment by orvice** [comment]
golang 1.5.3 编译出来正常，你们version多少？

```
INFO[0121] 5
INFO[0121] user port [21567] passwd or method change ,restart user...
INFO[0121] check finish...
INFO[0121] 5
INFO[0121] sync finish...
```

**Comment by kyledh** [comment]
版本也是1.5.3...

**Comment by glzjin** [comment]
1.4.3

**Comment by orvice** [comment]
@kyledh  @glzjin 这个问题fix了，编译个新版本试试看

**Comment by glzjin** [comment]
好，幸苦了，谢谢。
2016年3月2日 下午9:04，orvice notifications@github.com写道：@kyledh  @glzjin 这个问题fix了，编译个新版本试试看

**Comment by kyledh** [comment]
已测试，正常了。thx

**Comment by glzjin** [comment]
已测试，ok了。谢谢。

**Comment by glzjin** [comment]
`ERRO[0304] error listening port 30527: listen tcp :30527: bind: address already in use`

然而仍旧出现了这个问题哦= =

觉得是在切换端口上的密码和加密方式的时候处理方式不当，没把之前的监听给干掉。。。。

**Comment by orvice** [comment]
重启的时候是有干掉的

**Comment by glzjin** [comment]
> INFO[0120] 166
> INFO[0120] user port [30527] passwd or method change ,restart user...
> INFO[0120] check finish...
> INFO[0120] server listening port 30527 ...
> 
> INFO[0120] 166
> INFO[0120] sync finish...
> INFO[0180] 166
> INFO[0180] sync finish...
> INFO[0180] 166
> INFO[0180] user port [30527] passwd or method change ,restart user...
> INFO[0180] check finish...
> ERRO[0180] error listening port 30527: listen tcp :30527: bind: address already in use

第一次切换成功，第二次就不行了。。。。

**Comment by glzjin** [comment]
重新换了台干净的机子编译，正常了，谢谢。

**Comment by glzjin** [comment]
> DEBU[0120] check user for 30526
> DEBU[0120] check user for 30527
> INFO[0120] user port [30527] passwd or method change ,restart user...
> DEBU[0120] check user for 30528
> DEBU[0120] check user for 30529
> DEBU[0120] check user for 30530
> INFO[0120] check finish...
> ERRO[0120] error listening port 30527: listen tcp :30527: bind: address already in use

然而= =

**Comment by Acris** [comment]
我也遇到这个问题了，@orvice，ss-panel用户后台更换加密方式后会提示地址被占用然后退出程序，看样子这个BUG还没完全解决。

![捕获.PNG](https://ooo.0o0.ooo/2016/03/05/56db1e187e01b.png)
